# Questions from Trivia DB
question_data = [
    {"category": "Science: Computers", "type": "multiple", "difficulty": "easy",
    "question": "What does CPU stand for?",
    "correct_answer": "Central Processing Unit",
    "incorrect_answers": ["Central Process Unit", "Computer Personal Unit", "Central Processor Unit"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "medium",
    "question": "Moore&#039;s law originally stated that the number of transistors on a microprocessor chip would double every...",
    "correct_answer": "Year", "incorrect_answers": ["Four Years", "Two Years", "Eight Years"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "medium",
     "question": "What does AD stand for in relation to Windows Operating Systems? ",
     "correct_answer": "Active Directory",
     "incorrect_answers": ["Alternative Drive", "Automated Database", "Active Department"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "medium",
     "question": "When was the programming language &quot;C#&quot; released?", "correct_answer": "2000",
     "incorrect_answers": ["1998", "1999", "2001"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "easy",
     "question": "What amount of bits commonly equals one byte?", "correct_answer": "8",
     "incorrect_answers": ["1", "2", "64"]}, {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
                                              "question": "The programming language &quot;Python&quot; is based off a modified version of &quot;JavaScript&quot;.",
                                              "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
     "question": "Pointers were not used in the original C programming language; they were added later on in C++.",
     "correct_answer": "False", "incorrect_answers": ["True"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "hard",
     "question": "The internet domain .fm is the country-code top-level domain for which Pacific Ocean island nation?",
     "correct_answer": "Micronesia", "incorrect_answers": ["Fiji", "Tuvalu", "Marshall Islands"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "hard",
     "question": "What is the name of the process that sends one qubit of information using two bits of classical information?",
     "correct_answer": "Quantum Teleportation",
     "incorrect_answers": ["Super Dense Coding", "Quantum Entanglement", "Quantum Programming"]},
    {"category": "Science: Computers", "type": "multiple", "difficulty": "easy",
     "question": "In computing, what does MIDI stand for?", "correct_answer": "Musical Instrument Digital Interface",
     "incorrect_answers": ["Musical Interface of Digital Instruments", "Modular Interface of Digital Instruments",
                           "Musical Instrument Data Interface"]}]
